// utils/defaultFields.ts

export const defaultFields: Record<string, any> = {
  login: {
    email: '',
    password: '',
  },
  users: {
    firstName: '',
    lastName: '',
    email: '',
    // isConfirmed: true,
    phoneNumber: '',
    // password: '',
    role: 'admin',
  },
  blogs: {
    userId: '',
    name: '',
    title: '',
    content: '',
    slug: '',
    imageURL: '',
    status: '',
    publishedAt: new Date().toISOString(),
  },
  multimedias: {
    userId: '',
    name: '',
    title: '',
    content: '',
    mediaType: '',
    mediaURL: '',
    // thumbnailURL: '',
    // fileSize: 0,
    mimeType: '',
    tags: [],
    publishedAt: '',
    status: '',
  },
  publications: {
    userId: '',
    name: '',
    title: '',
    content: '',
    slug: '',
    author: '',
    imageURL: '',
    fileURL: '',
    published_at: '',
    status: '',
  },
  trainings: {
    userId: "...",
    name: "...",
    title: "...",
    content: "...",
    slug: "...",
    trainingType: "...",
    location: "...",
    startDate: new Date().toISOString(),
    endDate: new Date().toISOString(),
    durationHours: 0,
    imageURL: "...",
    certification: true,
    status: "...",
  },
  owners: {
    name: '',
    email: '',
    logo_url: '',
    primary_color: '',
    title: '',
    font_family: '',
    font_url: '',
  },
  links: {
    owner_id: '',
    label: '',
    url: '',
  },
  phones: {
    owner_id: '',
    number: '',
  },
  locations: {
    owner_id: '',
    address: '',
    lat: 0,
    lng: 0,
  },
  sections: {
    key: '',
    title: '',
    description: '',
  },
  services: {
    section_id: '',
    title: '',
    content: '',
    image_url: '',
    slug: '',
  },
  teams: {
    section_id: '',
    name: '',
    email: '',
    linkedin: '',
    facebook: '',
    position: '',
    image_url: '',
  },
  partners: {
    section_id: '...',
    name: '...',
    logo_url: "...",
    link: 'https://...',
  },
  projects: {
    section_id: '',
    title: '',
    description: '',
    date: '',
    client: '',
  },
  // "what-we-do-images": {
  //   section_id: '',
  //   title: '',
  //   description: '',
  //   image_url: '',
  // },
  about_us: {
    description1: '',
    description2: '',
    image_url: 'https://...',
  },
  gallery: {
    title: '...',
    description: '...',
    image_url: 'https://...',
    video_url: 'https://...',
    // type: '...',
    // thumbnail_url?: string;
  },
  expertise: {
    title: '...',
    description: '...',
    image_url: 'https://...',
  }
};
